# Generated by Django 4.2.7 on 2025-11-15 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('ssn', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('ACTIVE', 'Active Client'), ('LAPSED', 'Lapsed'), ('CANCELLED', 'Cancelled')], default='PROSPECT', max_length=50)),
                ('first_contact_date', models.DateField(default=django.utils.timezone.now)),
                ('last_contact_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='InsuranceAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=50, unique=True)),
                ('license_number', models.CharField(max_length=100)),
                ('agency_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('specialties', models.JSONField(default=list)),
                ('certification_level', models.CharField(choices=[('BASIC', 'Basic Certification'), ('INTERMEDIATE', 'Intermediate Certification'), ('ADVANCED', 'Advanced Certification'), ('MASTER', 'Master Agent')], default='BASIC', max_length=50)),
                ('active_since', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurance_agents',
            },
        ),
        migrations.CreateModel(
            name='InsuranceCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(choices=[('HEALTH', 'Health Insurance'), ('DENTAL', 'Dental Insurance'), ('VISION', 'Vision Insurance'), ('LIFE', 'Life Insurance'), ('DISABILITY', 'Disability Insurance')], max_length=50)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'insurance_carriers',
            },
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('plan_code', models.CharField(max_length=50)),
                ('plan_type', models.CharField(choices=[('PPO', 'Preferred Provider Organization'), ('HMO', 'Health Maintenance Organization'), ('EPO', 'Exclusive Provider Organization'), ('POS', 'Point of Service'), ('HDHP', 'High Deductible Health Plan')], max_length=50)),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], max_length=50)),
                ('monthly_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_deductible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_out_of_pocket', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coinsurance_percentage', models.IntegerField(default=20)),
                ('pcp_copay', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('specialist_copay', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('urgent_care_copay', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('er_copay', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('requires_referrals', models.BooleanField(default=False)),
                ('out_of_network_coverage', models.BooleanField(default=False)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='insurance.insurancecarrier')),
            ],
            options={
                'db_table': 'insurance_plans',
                'unique_together': {('carrier', 'plan_code')},
            },
        ),
        migrations.CreateModel(
            name='PolicyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=100, unique=True)),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('requested_effective_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=50)),
                ('monthly_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('declined_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='insurance.insuranceagent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='insurance.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='insurance.insuranceplan')),
            ],
            options={
                'db_table': 'policy_applications',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='insurance.insuranceagent'),
        ),
        migrations.CreateModel(
            name='AgentCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('INITIAL', 'Initial Commission'), ('RENEWAL', 'Renewal Commission'), ('BONUS', 'Bonus Commission'), ('OVERRIDE', 'Override Commission')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pay_period', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CALCULATED', 'Calculated'), ('PAID', 'Paid'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=50)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='insurance.insuranceagent')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='insurance.policyapplication')),
            ],
            options={
                'db_table': 'agent_commissions',
            },
        ),
        migrations.CreateModel(
            name='AgentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('QUOTE', 'Quote Generated'), ('APPLICATION', 'Application Submitted'), ('FOLLOW_UP', 'Follow Up'), ('POLICY_CHANGE', 'Policy Change'), ('CLAIM_ASSISTANCE', 'Claim Assistance')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('outcome', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('scheduled_follow_up', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='insurance.insuranceagent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='insurance.client')),
            ],
            options={
                'db_table': 'agent_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
